### PR TITLE
added separate tsconfig for enzyme inheriting project configuration

### PR DESCRIPTION
**Pull request by baywet**
this avoids having lots of issues when trying to run unit tests

### CODE REVIEW

**Comment by baywet** [comment]
I created a second one because I didn't want the one we need for the ts-jest to conflict with the one you need to build the current package.
IE: for the current package you need to include those
```JSON
"include": [
    "postinstall/*.ts"
  ],
```
and you only load the node libraries.

Unit tests on an SPFx project need more than that/different things.

So the reasons are:
- separation of concerns (both for the consumer project and the current project)
- overriding only what we need (hence the extend) / staying as close as possible to the SPFx configuration

**Comment by andrewconnell** [comment]
Got it... makes sense and a good idea. I'm going to change what you've done though to make it clearer as right now **/resources/tsconfig.json** isn't obvious what it's used for. Thanks!

**Comment by baywet** [comment]
Feel free to edit my PR. You should have permissions.

**Comment by andrewconnell** [comment]
Closing due to being outdated. Great suggestion and used it as the baseline for the fix in v1.3.2

**Pull request closed without merging**
